name: fluxer_dart
version: 2.0.0
description: Dart SDK for Fluxer a free and open source instant messaging and VoIP platform.
homepage: https://fluxer.app
repository: https://github.com/fluxerapp/dart_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: "^5.7.0"
  json_annotation: "^4.9.0"
  retrofit: "^4.4.1"

dev_dependencies:
  json_serializable: "^6.9.0"
  retrofit_generator: ^10.2.3
  build_runner: any
  test: "^1.16.0"
