//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:fluxer_dart/src/model/api_error_code.dart';
import 'package:fluxer_dart/src/model/validation_error_item.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'error.g.dart';

/// Error
///
/// Properties:
/// * [code]
/// * [message] - Human-readable error message
/// * [errors] - Field-specific validation errors
@BuiltValue()
abstract class Error implements Built<Error, ErrorBuilder> {
  @BuiltValueField(wireName: r'code')
  APIErrorCode get code;
  // enum codeEnum {  ACCESS_DENIED,  ACCOUNT_DISABLED,  BAD_GATEWAY,  BAD_REQUEST,  BLUESKY_OAUTH_CALLBACK_FAILED,  BLUESKY_OAUTH_NOT_ENABLED,  BLUESKY_OAUTH_SESSION_EXPIRED,  BLUESKY_OAUTH_STATE_INVALID,  ACCOUNT_SCHEDULED_FOR_DELETION,  ACCOUNT_SUSPENDED_PERMANENTLY,  ACCOUNT_SUSPENDED_TEMPORARILY,  ACCOUNT_SUSPICIOUS_ACTIVITY,  ACCOUNT_TOO_NEW_FOR_GUILD,  ACLS_MUST_BE_NON_EMPTY,  ADMIN_API_KEY_NOT_FOUND,  APPLICATION_NOT_FOUND,  APPLICATION_NOT_OWNED,  ALREADY_FRIENDS,  AUDIT_LOG_INDEXING,  BOTS_CANNOT_SEND_FRIEND_REQUESTS,  BOT_ALREADY_IN_GUILD,  BOT_APPLICATION_NOT_FOUND,  BOT_IS_PRIVATE,  BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED,  BOT_USER_AUTH_SESSION_CREATION_DENIED,  BOT_USER_GENERATION_FAILED,  BOT_USER_NOT_FOUND,  CALL_ALREADY_EXISTS,  CANNOT_EDIT_OTHER_USER_MESSAGE,  CANNOT_EXECUTE_ON_DM,  CANNOT_MODIFY_SYSTEM_WEBHOOK,  CANNOT_MODIFY_VOICE_STATE,  CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY,  CANNOT_REPORT_OWN_GUILD,  CANNOT_REPORT_OWN_MESSAGE,  CANNOT_REPORT_YOURSELF,  CANNOT_SEND_EMPTY_MESSAGE,  CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER,  CANNOT_SEND_FRIEND_REQUEST_TO_SELF,  CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL,  CANNOT_SEND_MESSAGES_TO_USER,  CANNOT_TRANSFER_OWNERSHIP_TO_BOT,  CANNOT_SHRINK_RESERVED_SLOTS,  CAPTCHA_REQUIRED,  CHANNEL_INDEXING,  COMMUNICATION_DISABLED,  CONNECTION_ALREADY_EXISTS,  CONNECTION_INITIATION_TOKEN_INVALID,  CONNECTION_INVALID_IDENTIFIER,  CONNECTION_INVALID_TYPE,  CONNECTION_LIMIT_REACHED,  CONNECTION_NOT_FOUND,  CONNECTION_VERIFICATION_FAILED,  CONFLICT,  CONTENT_BLOCKED,  CREATION_FAILED,  CSAM_SCAN_FAILED,  CSAM_SCAN_PARSE_ERROR,  CSAM_SCAN_SUBSCRIPTION_ERROR,  CSAM_SCAN_TIMEOUT,  DECRYPTION_FAILED,  DELETION_FAILED,  DISCOVERY_ALREADY_APPLIED,  DISCOVERY_APPLICATION_ALREADY_REVIEWED,  DISCOVERY_APPLICATION_NOT_FOUND,  DISCOVERY_DESCRIPTION_REQUIRED,  DISCOVERY_DISABLED,  DISCOVERY_INSUFFICIENT_MEMBERS,  DISCOVERY_INVALID_CATEGORY,  DISCOVERY_NOT_DISCOVERABLE,  DISCRIMINATOR_REQUIRED,  EMAIL_SERVICE_NOT_TESTABLE,  EMAIL_VERIFICATION_REQUIRED,  EMPTY_ENCRYPTED_BODY,  ENCRYPTION_FAILED,  EXPLICIT_CONTENT_CANNOT_BE_SENT,  FEATURE_NOT_AVAILABLE_SELF_HOSTED,  FEATURE_TEMPORARILY_DISABLED,  FILE_SIZE_TOO_LARGE,  FORBIDDEN,  FRIEND_REQUEST_BLOCKED,  GATEWAY_TIMEOUT,  GENERAL_ERROR,  GONE,  GIFT_CODE_ALREADY_REDEEMED,  GUILD_PHONE_VERIFICATION_REQUIRED,  GUILD_VERIFICATION_REQUIRED,  HANDOFF_CODE_EXPIRED,  HARVEST_EXPIRED,  HARVEST_FAILED,  HARVEST_NOT_READY,  HARVEST_ON_COOLDOWN,  HTTP_GET_AUTHORIZE_NOT_SUPPORTED,  INSTANCE_VERSION_MISMATCH,  INTERNAL_SERVER_ERROR,  INVALID_ACLS_FORMAT,  INVALID_API_ORIGIN,  INVALID_AUTH_TOKEN,  INVALID_BOT_FLAG,  INVALID_CAPTCHA,  INVALID_CHANNEL_TYPE_FOR_CALL,  INVALID_CHANNEL_TYPE,  INVALID_CLIENT,  INVALID_CLIENT_SECRET,  INVALID_DSA_REPORT_TARGET,  INVALID_DSA_TICKET,  INVALID_DSA_VERIFICATION_CODE,  INVALID_DECRYPTED_JSON,  INVALID_EPHEMERAL_KEY,  INVALID_FLAGS_FORMAT,  INVALID_IV,  INVALID_FORM_BODY,  INVALID_GRANT,  INVALID_HANDOFF_CODE,  INVALID_PACK_TYPE,  INVALID_PERMISSIONS_INTEGER,  INVALID_PERMISSIONS_NEGATIVE,  INVALID_PHONE_NUMBER,  INVALID_PHONE_VERIFICATION_CODE,  INVALID_REDIRECT_URI,  INVALID_REQUEST,  INVALID_RESPONSE_TYPE_FOR_NON_BOT,  INVALID_SCOPE,  INVALID_STREAM_KEY_FORMAT,  INVALID_STREAM_THUMBNAIL_PAYLOAD,  INVALID_SUDO_TOKEN,  INVALID_SUSPICIOUS_FLAGS_FORMAT,  INVALID_SYSTEM_FLAG,  INVALID_TIMESTAMP,  INVALID_TOKEN,  INVALID_WEBAUTHN_AUTHENTICATION_COUNTER,  INVALID_WEBAUTHN_CREDENTIAL_COUNTER,  INVALID_WEBAUTHN_CREDENTIAL,  INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT,  INVITES_DISABLED,  IP_AUTHORIZATION_REQUIRED,  IP_AUTHORIZATION_RESEND_COOLDOWN,  IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED,  IP_BANNED,  MAX_ANIMATED_EMOJIS,  MAX_BOOKMARKS,  MAX_CATEGORY_CHANNELS,  MAX_EMOJIS,  MAX_FAVORITE_MEMES,  MAX_FRIENDS,  MAX_GROUP_DM_RECIPIENTS,  MAX_GROUP_DMS,  MAX_GUILD_CHANNELS,  MAX_GUILD_MEMBERS,  MAX_GUILD_ROLES,  MAX_GUILDS,  MAX_INVITES,  MAX_PACK_EXPRESSIONS,  MAX_PACKS,  MAX_PINS_PER_CHANNEL,  MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE,  MAX_REACTIONS,  MAX_STICKERS,  MAX_WEBHOOKS_PER_CHANNEL,  MAX_WEBHOOKS_PER_GUILD,  MAX_WEBHOOKS,  NCMEC_ALREADY_SUBMITTED,  NCMEC_SUBMISSION_FAILED,  MEDIA_METADATA_ERROR,  METHOD_NOT_ALLOWED,  MISSING_ACCESS,  MISSING_ACL,  MISSING_AUTHORIZATION,  MISSING_CLIENT_SECRET,  MISSING_EPHEMERAL_KEY,  MISSING_IV,  MISSING_OAUTH_ADMIN_SCOPE,  MISSING_OAUTH_FIELDS,  MISSING_OAUTH_SCOPE,  MISSING_PERMISSIONS,  MISSING_REDIRECT_URI,  NO_ACTIVE_CALL,  NO_ACTIVE_SUBSCRIPTION,  NOT_FOUND,  NOT_IMPLEMENTED,  NO_PASSKEYS_REGISTERED,  NO_PENDING_DELETION,  NO_USERS_WITH_FLUXERTAG_EXIST,  NO_VISIONARY_SLOTS_AVAILABLE,  NOT_A_BOT_APPLICATION,  NOT_FRIENDS_WITH_USER,  NOT_OWNER_OF_ADMIN_API_KEY,  NSFW_CONTENT_AGE_RESTRICTED,  PACK_ACCESS_DENIED,  PASSKEY_AUTHENTICATION_FAILED,  PASSKEYS_DISABLED,  PHONE_ALREADY_USED,  PHONE_RATE_LIMIT_EXCEEDED,  PHONE_REQUIRED_FOR_SMS_MFA,  PHONE_VERIFICATION_REQUIRED,  PREMIUM_PURCHASE_BLOCKED,  PREVIEW_MUST_BE_JPEG,  PROCESSING_FAILED,  RATE_LIMITED,  REDIRECT_URI_REQUIRED_FOR_NON_BOT,  REPORT_ALREADY_RESOLVED,  REPORT_BANNED,  RESPONSE_VALIDATION_ERROR,  SERVICE_UNAVAILABLE,  SESSION_TOKEN_MISMATCH,  SLOWMODE_RATE_LIMITED,  SMS_MFA_NOT_ENABLED,  SMS_MFA_REQUIRES_TOTP,  SMS_VERIFICATION_UNAVAILABLE,  SSO_REQUIRED,  STREAM_KEY_CHANNEL_MISMATCH,  STREAM_KEY_SCOPE_MISMATCH,  STREAM_THUMBNAIL_PAYLOAD_EMPTY,  STRIPE_ERROR,  STRIPE_GIFT_REDEMPTION_IN_PROGRESS,  STRIPE_INVALID_PRODUCT,  STRIPE_INVALID_PRODUCT_CONFIGURATION,  STRIPE_NO_ACTIVE_SUBSCRIPTION,  STRIPE_NO_PURCHASE_HISTORY,  STRIPE_NO_SUBSCRIPTION,  STRIPE_PAYMENT_NOT_AVAILABLE,  STRIPE_SUBSCRIPTION_ALREADY_CANCELING,  STRIPE_SUBSCRIPTION_NOT_CANCELING,  STRIPE_SUBSCRIPTION_PERIOD_END_MISSING,  STRIPE_WEBHOOK_NOT_AVAILABLE,  STRIPE_WEBHOOK_SIGNATURE_INVALID,  STRIPE_WEBHOOK_SIGNATURE_MISSING,  DONATION_AMOUNT_INVALID,  DONATION_MAGIC_LINK_EXPIRED,  DONATION_MAGIC_LINK_INVALID,  DONATION_MAGIC_LINK_USED,  DONOR_NOT_FOUND,  SUDO_MODE_REQUIRED,  TAG_ALREADY_TAKEN,  TEMPORARY_INVITE_REQUIRES_PRESENCE,  TEST_HARNESS_DISABLED,  TEST_HARNESS_FORBIDDEN,  TWO_FA_NOT_ENABLED,  TWO_FACTOR_REQUIRED,  UNAUTHORIZED,  UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS,  UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS,  UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS,  UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS,  UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS,  UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS,  UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES,  UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES,  UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS,  UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES,  UNKNOWN_CHANNEL,  UNKNOWN_EMOJI,  UNKNOWN_FAVORITE_MEME,  UNKNOWN_GIFT_CODE,  UNKNOWN_GUILD,  UNKNOWN_HARVEST,  UNKNOWN_INVITE,  UNKNOWN_MEMBER,  UNKNOWN_MESSAGE,  UNKNOWN_PACK,  UNKNOWN_REPORT,  UNKNOWN_ROLE,  UNKNOWN_STICKER,  UNKNOWN_SUSPICIOUS_FLAG,  UNKNOWN_USER_FLAG,  UNKNOWN_USER,  UNKNOWN_VOICE_REGION,  UNKNOWN_VOICE_SERVER,  UNKNOWN_WEBAUTHN_CREDENTIAL,  UNKNOWN_APPLICATION,  UNKNOWN_WEBHOOK,  UNSUPPORTED_RESPONSE_TYPE,  USERNAME_NOT_AVAILABLE,  UPDATE_FAILED,  USER_BANNED_FROM_GUILD,  USER_IP_BANNED_FROM_GUILD,  USER_NOT_IN_VOICE,  USER_OWNS_GUILDS,  VALIDATION_ERROR,  VOICE_CHANNEL_FULL,  WEBAUTHN_CREDENTIAL_LIMIT_REACHED,  };

  /// Human-readable error message
  @BuiltValueField(wireName: r'message')
  String get message;

  /// Field-specific validation errors
  @BuiltValueField(wireName: r'errors')
  BuiltList<ValidationErrorItem>? get errors;

  Error._();

  factory Error([void updates(ErrorBuilder b)]) = _$Error;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(ErrorBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<Error> get serializer => _$ErrorSerializer();
}

class _$ErrorSerializer implements PrimitiveSerializer<Error> {
  @override
  final Iterable<Type> types = const [Error, _$Error];

  @override
  final String wireName = r'Error';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    Error object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'code';
    yield serializers.serialize(
      object.code,
      specifiedType: const FullType(APIErrorCode),
    );
    yield r'message';
    yield serializers.serialize(
      object.message,
      specifiedType: const FullType(String),
    );
    if (object.errors != null) {
      yield r'errors';
      yield serializers.serialize(
        object.errors,
        specifiedType:
            const FullType(BuiltList, [FullType(ValidationErrorItem)]),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    Error object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object,
            specifiedType: specifiedType)
        .toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required ErrorBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'code':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(APIErrorCode),
          ) as APIErrorCode;
          result.code = valueDes;
          break;
        case r'message':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.message = valueDes;
          break;
        case r'errors':
          final valueDes = serializers.deserialize(
            value,
            specifiedType:
                const FullType(BuiltList, [FullType(ValidationErrorItem)]),
          ) as BuiltList<ValidationErrorItem>;
          result.errors.replace(valueDes);
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  Error deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = ErrorBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}
