// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import, invalid_annotation_target, unnecessary_import

import 'package:json_annotation/json_annotation.dart';

/// Error codes returned by API operations
@JsonEnum()
enum ApiErrorCode {
  @JsonValue('ACCESS_DENIED')
  accessDenied('ACCESS_DENIED'),
  @JsonValue('ACCOUNT_DISABLED')
  accountDisabled('ACCOUNT_DISABLED'),
  @JsonValue('BAD_GATEWAY')
  badGateway('BAD_GATEWAY'),
  @JsonValue('BAD_REQUEST')
  badRequest('BAD_REQUEST'),
  @JsonValue('BLUESKY_OAUTH_AUTHORIZATION_FAILED')
  blueskyOauthAuthorizationFailed('BLUESKY_OAUTH_AUTHORIZATION_FAILED'),
  @JsonValue('BLUESKY_OAUTH_CALLBACK_FAILED')
  blueskyOauthCallbackFailed('BLUESKY_OAUTH_CALLBACK_FAILED'),
  @JsonValue('BLUESKY_OAUTH_NOT_ENABLED')
  blueskyOauthNotEnabled('BLUESKY_OAUTH_NOT_ENABLED'),
  @JsonValue('BLUESKY_OAUTH_SESSION_EXPIRED')
  blueskyOauthSessionExpired('BLUESKY_OAUTH_SESSION_EXPIRED'),
  @JsonValue('BLUESKY_OAUTH_STATE_INVALID')
  blueskyOauthStateInvalid('BLUESKY_OAUTH_STATE_INVALID'),
  @JsonValue('ACCOUNT_SCHEDULED_FOR_DELETION')
  accountScheduledForDeletion('ACCOUNT_SCHEDULED_FOR_DELETION'),
  @JsonValue('ACCOUNT_SUSPENDED_PERMANENTLY')
  accountSuspendedPermanently('ACCOUNT_SUSPENDED_PERMANENTLY'),
  @JsonValue('ACCOUNT_SUSPENDED_TEMPORARILY')
  accountSuspendedTemporarily('ACCOUNT_SUSPENDED_TEMPORARILY'),
  @JsonValue('ACCOUNT_SUSPICIOUS_ACTIVITY')
  accountSuspiciousActivity('ACCOUNT_SUSPICIOUS_ACTIVITY'),
  @JsonValue('ACCOUNT_TOO_NEW_FOR_GUILD')
  accountTooNewForGuild('ACCOUNT_TOO_NEW_FOR_GUILD'),
  @JsonValue('ACLS_MUST_BE_NON_EMPTY')
  aclsMustBeNonEmpty('ACLS_MUST_BE_NON_EMPTY'),
  @JsonValue('ADMIN_API_KEY_NOT_FOUND')
  adminApiKeyNotFound('ADMIN_API_KEY_NOT_FOUND'),
  @JsonValue('APPLICATION_NOT_FOUND')
  applicationNotFound('APPLICATION_NOT_FOUND'),
  @JsonValue('APPLICATION_NOT_OWNED')
  applicationNotOwned('APPLICATION_NOT_OWNED'),
  @JsonValue('ALREADY_FRIENDS')
  alreadyFriends('ALREADY_FRIENDS'),
  @JsonValue('AUDIT_LOG_INDEXING')
  auditLogIndexing('AUDIT_LOG_INDEXING'),
  @JsonValue('BOTS_CANNOT_SEND_FRIEND_REQUESTS')
  botsCannotSendFriendRequests('BOTS_CANNOT_SEND_FRIEND_REQUESTS'),
  @JsonValue('BOT_ALREADY_IN_GUILD')
  botAlreadyInGuild('BOT_ALREADY_IN_GUILD'),
  @JsonValue('BOT_APPLICATION_NOT_FOUND')
  botApplicationNotFound('BOT_APPLICATION_NOT_FOUND'),
  @JsonValue('BOT_IS_PRIVATE')
  botIsPrivate('BOT_IS_PRIVATE'),
  @JsonValue('BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED')
  botUserAuthEndpointAccessDenied('BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED'),
  @JsonValue('BOT_USER_AUTH_SESSION_CREATION_DENIED')
  botUserAuthSessionCreationDenied('BOT_USER_AUTH_SESSION_CREATION_DENIED'),
  @JsonValue('BOT_USER_GENERATION_FAILED')
  botUserGenerationFailed('BOT_USER_GENERATION_FAILED'),
  @JsonValue('BOT_USER_NOT_FOUND')
  botUserNotFound('BOT_USER_NOT_FOUND'),
  @JsonValue('CALL_ALREADY_EXISTS')
  callAlreadyExists('CALL_ALREADY_EXISTS'),
  @JsonValue('CANNOT_EDIT_OTHER_USER_MESSAGE')
  cannotEditOtherUserMessage('CANNOT_EDIT_OTHER_USER_MESSAGE'),
  @JsonValue('CANNOT_EXECUTE_ON_DM')
  cannotExecuteOnDm('CANNOT_EXECUTE_ON_DM'),
  @JsonValue('CANNOT_MODIFY_SYSTEM_WEBHOOK')
  cannotModifySystemWebhook('CANNOT_MODIFY_SYSTEM_WEBHOOK'),
  @JsonValue('CANNOT_MODIFY_VOICE_STATE')
  cannotModifyVoiceState('CANNOT_MODIFY_VOICE_STATE'),
  @JsonValue('CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY')
  cannotRedeemPlutoniumWithVisionary('CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY'),
  @JsonValue('CANNOT_REPORT_OWN_GUILD')
  cannotReportOwnGuild('CANNOT_REPORT_OWN_GUILD'),
  @JsonValue('CANNOT_REPORT_OWN_MESSAGE')
  cannotReportOwnMessage('CANNOT_REPORT_OWN_MESSAGE'),
  @JsonValue('CANNOT_REPORT_YOURSELF')
  cannotReportYourself('CANNOT_REPORT_YOURSELF'),
  @JsonValue('CANNOT_SEND_EMPTY_MESSAGE')
  cannotSendEmptyMessage('CANNOT_SEND_EMPTY_MESSAGE'),
  @JsonValue('CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER')
  cannotSendFriendRequestToBlockedUser(
    'CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER',
  ),
  @JsonValue('CANNOT_SEND_FRIEND_REQUEST_TO_SELF')
  cannotSendFriendRequestToSelf('CANNOT_SEND_FRIEND_REQUEST_TO_SELF'),
  @JsonValue('CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL')
  cannotSendMessagesInNonTextChannel(
    'CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL',
  ),
  @JsonValue('CANNOT_SEND_MESSAGES_TO_USER')
  cannotSendMessagesToUser('CANNOT_SEND_MESSAGES_TO_USER'),
  @JsonValue('CANNOT_TRANSFER_OWNERSHIP_TO_BOT')
  cannotTransferOwnershipToBot('CANNOT_TRANSFER_OWNERSHIP_TO_BOT'),
  @JsonValue('CANNOT_SHRINK_RESERVED_SLOTS')
  cannotShrinkReservedSlots('CANNOT_SHRINK_RESERVED_SLOTS'),
  @JsonValue('CAPTCHA_REQUIRED')
  captchaRequired('CAPTCHA_REQUIRED'),
  @JsonValue('CHANNEL_INDEXING')
  channelIndexing('CHANNEL_INDEXING'),
  @JsonValue('COMMUNICATION_DISABLED')
  communicationDisabled('COMMUNICATION_DISABLED'),
  @JsonValue('CONNECTION_ALREADY_EXISTS')
  connectionAlreadyExists('CONNECTION_ALREADY_EXISTS'),
  @JsonValue('CONNECTION_INITIATION_TOKEN_INVALID')
  connectionInitiationTokenInvalid('CONNECTION_INITIATION_TOKEN_INVALID'),
  @JsonValue('CONNECTION_INVALID_IDENTIFIER')
  connectionInvalidIdentifier('CONNECTION_INVALID_IDENTIFIER'),
  @JsonValue('CONNECTION_INVALID_TYPE')
  connectionInvalidType('CONNECTION_INVALID_TYPE'),
  @JsonValue('CONNECTION_LIMIT_REACHED')
  connectionLimitReached('CONNECTION_LIMIT_REACHED'),
  @JsonValue('CONNECTION_NOT_FOUND')
  connectionNotFound('CONNECTION_NOT_FOUND'),
  @JsonValue('CONNECTION_VERIFICATION_FAILED')
  connectionVerificationFailed('CONNECTION_VERIFICATION_FAILED'),
  @JsonValue('CONFLICT')
  conflict('CONFLICT'),
  @JsonValue('CONTENT_BLOCKED')
  contentBlocked('CONTENT_BLOCKED'),
  @JsonValue('CREATION_FAILED')
  creationFailed('CREATION_FAILED'),
  @JsonValue('CSAM_SCAN_FAILED')
  csamScanFailed('CSAM_SCAN_FAILED'),
  @JsonValue('CSAM_SCAN_PARSE_ERROR')
  csamScanParseError('CSAM_SCAN_PARSE_ERROR'),
  @JsonValue('CSAM_SCAN_SUBSCRIPTION_ERROR')
  csamScanSubscriptionError('CSAM_SCAN_SUBSCRIPTION_ERROR'),
  @JsonValue('CSAM_SCAN_TIMEOUT')
  csamScanTimeout('CSAM_SCAN_TIMEOUT'),
  @JsonValue('DECRYPTION_FAILED')
  decryptionFailed('DECRYPTION_FAILED'),
  @JsonValue('DELETION_FAILED')
  deletionFailed('DELETION_FAILED'),
  @JsonValue('DISCOVERY_ALREADY_APPLIED')
  discoveryAlreadyApplied('DISCOVERY_ALREADY_APPLIED'),
  @JsonValue('DISCOVERY_APPLICATION_ALREADY_REVIEWED')
  discoveryApplicationAlreadyReviewed('DISCOVERY_APPLICATION_ALREADY_REVIEWED'),
  @JsonValue('DISCOVERY_APPLICATION_NOT_FOUND')
  discoveryApplicationNotFound('DISCOVERY_APPLICATION_NOT_FOUND'),
  @JsonValue('DISCOVERY_DESCRIPTION_REQUIRED')
  discoveryDescriptionRequired('DISCOVERY_DESCRIPTION_REQUIRED'),
  @JsonValue('DISCOVERY_DISABLED')
  discoveryDisabled('DISCOVERY_DISABLED'),
  @JsonValue('DISCOVERY_INSUFFICIENT_MEMBERS')
  discoveryInsufficientMembers('DISCOVERY_INSUFFICIENT_MEMBERS'),
  @JsonValue('DISCOVERY_INVALID_CATEGORY')
  discoveryInvalidCategory('DISCOVERY_INVALID_CATEGORY'),
  @JsonValue('DISCOVERY_NOT_DISCOVERABLE')
  discoveryNotDiscoverable('DISCOVERY_NOT_DISCOVERABLE'),
  @JsonValue('DISCRIMINATOR_REQUIRED')
  discriminatorRequired('DISCRIMINATOR_REQUIRED'),
  @JsonValue('EMAIL_SERVICE_NOT_TESTABLE')
  emailServiceNotTestable('EMAIL_SERVICE_NOT_TESTABLE'),
  @JsonValue('EMAIL_VERIFICATION_REQUIRED')
  emailVerificationRequired('EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('EMPTY_ENCRYPTED_BODY')
  emptyEncryptedBody('EMPTY_ENCRYPTED_BODY'),
  @JsonValue('ENCRYPTION_FAILED')
  encryptionFailed('ENCRYPTION_FAILED'),
  @JsonValue('EXPLICIT_CONTENT_CANNOT_BE_SENT')
  explicitContentCannotBeSent('EXPLICIT_CONTENT_CANNOT_BE_SENT'),
  @JsonValue('FEATURE_NOT_AVAILABLE_SELF_HOSTED')
  featureNotAvailableSelfHosted('FEATURE_NOT_AVAILABLE_SELF_HOSTED'),
  @JsonValue('FEATURE_TEMPORARILY_DISABLED')
  featureTemporarilyDisabled('FEATURE_TEMPORARILY_DISABLED'),
  @JsonValue('FILE_SIZE_TOO_LARGE')
  fileSizeTooLarge('FILE_SIZE_TOO_LARGE'),
  @JsonValue('FORBIDDEN')
  forbidden('FORBIDDEN'),
  @JsonValue('FRIEND_REQUEST_BLOCKED')
  friendRequestBlocked('FRIEND_REQUEST_BLOCKED'),
  @JsonValue('GATEWAY_TIMEOUT')
  gatewayTimeout('GATEWAY_TIMEOUT'),
  @JsonValue('GENERAL_ERROR')
  generalError('GENERAL_ERROR'),
  @JsonValue('GONE')
  gone('GONE'),
  @JsonValue('GIFT_CODE_ALREADY_REDEEMED')
  giftCodeAlreadyRedeemed('GIFT_CODE_ALREADY_REDEEMED'),
  @JsonValue('GUILD_PHONE_VERIFICATION_REQUIRED')
  guildPhoneVerificationRequired('GUILD_PHONE_VERIFICATION_REQUIRED'),
  @JsonValue('GUILD_VERIFICATION_REQUIRED')
  guildVerificationRequired('GUILD_VERIFICATION_REQUIRED'),
  @JsonValue('HANDOFF_CODE_EXPIRED')
  handoffCodeExpired('HANDOFF_CODE_EXPIRED'),
  @JsonValue('HARVEST_EXPIRED')
  harvestExpired('HARVEST_EXPIRED'),
  @JsonValue('HARVEST_FAILED')
  harvestFailed('HARVEST_FAILED'),
  @JsonValue('HARVEST_NOT_READY')
  harvestNotReady('HARVEST_NOT_READY'),
  @JsonValue('HARVEST_ON_COOLDOWN')
  harvestOnCooldown('HARVEST_ON_COOLDOWN'),
  @JsonValue('HTTP_GET_AUTHORIZE_NOT_SUPPORTED')
  httpGetAuthorizeNotSupported('HTTP_GET_AUTHORIZE_NOT_SUPPORTED'),
  @JsonValue('INSTANCE_VERSION_MISMATCH')
  instanceVersionMismatch('INSTANCE_VERSION_MISMATCH'),
  @JsonValue('INTERNAL_SERVER_ERROR')
  internalServerError('INTERNAL_SERVER_ERROR'),
  @JsonValue('INVALID_ACLS_FORMAT')
  invalidAclsFormat('INVALID_ACLS_FORMAT'),
  @JsonValue('INVALID_API_ORIGIN')
  invalidApiOrigin('INVALID_API_ORIGIN'),
  @JsonValue('INVALID_AUTH_TOKEN')
  invalidAuthToken('INVALID_AUTH_TOKEN'),
  @JsonValue('INVALID_BOT_FLAG')
  invalidBotFlag('INVALID_BOT_FLAG'),
  @JsonValue('INVALID_CAPTCHA')
  invalidCaptcha('INVALID_CAPTCHA'),
  @JsonValue('INVALID_CHANNEL_TYPE_FOR_CALL')
  invalidChannelTypeForCall('INVALID_CHANNEL_TYPE_FOR_CALL'),
  @JsonValue('INVALID_CHANNEL_TYPE')
  invalidChannelType('INVALID_CHANNEL_TYPE'),
  @JsonValue('INVALID_CLIENT')
  invalidClient('INVALID_CLIENT'),
  @JsonValue('INVALID_CLIENT_SECRET')
  invalidClientSecret('INVALID_CLIENT_SECRET'),
  @JsonValue('INVALID_DSA_REPORT_TARGET')
  invalidDsaReportTarget('INVALID_DSA_REPORT_TARGET'),
  @JsonValue('INVALID_DSA_TICKET')
  invalidDsaTicket('INVALID_DSA_TICKET'),
  @JsonValue('INVALID_DSA_VERIFICATION_CODE')
  invalidDsaVerificationCode('INVALID_DSA_VERIFICATION_CODE'),
  @JsonValue('INVALID_DECRYPTED_JSON')
  invalidDecryptedJson('INVALID_DECRYPTED_JSON'),
  @JsonValue('INVALID_EPHEMERAL_KEY')
  invalidEphemeralKey('INVALID_EPHEMERAL_KEY'),
  @JsonValue('INVALID_FLAGS_FORMAT')
  invalidFlagsFormat('INVALID_FLAGS_FORMAT'),
  @JsonValue('INVALID_IV')
  invalidIv('INVALID_IV'),
  @JsonValue('INVALID_FORM_BODY')
  invalidFormBody('INVALID_FORM_BODY'),
  @JsonValue('INVALID_GRANT')
  invalidGrant('INVALID_GRANT'),
  @JsonValue('INVALID_HANDOFF_CODE')
  invalidHandoffCode('INVALID_HANDOFF_CODE'),
  @JsonValue('INVALID_PACK_TYPE')
  invalidPackType('INVALID_PACK_TYPE'),
  @JsonValue('INVALID_PERMISSIONS_INTEGER')
  invalidPermissionsInteger('INVALID_PERMISSIONS_INTEGER'),
  @JsonValue('INVALID_PERMISSIONS_NEGATIVE')
  invalidPermissionsNegative('INVALID_PERMISSIONS_NEGATIVE'),
  @JsonValue('INVALID_PHONE_NUMBER')
  invalidPhoneNumber('INVALID_PHONE_NUMBER'),
  @JsonValue('INVALID_PHONE_VERIFICATION_CODE')
  invalidPhoneVerificationCode('INVALID_PHONE_VERIFICATION_CODE'),
  @JsonValue('INVALID_REDIRECT_URI')
  invalidRedirectUri('INVALID_REDIRECT_URI'),
  @JsonValue('INVALID_REQUEST')
  invalidRequest('INVALID_REQUEST'),
  @JsonValue('INVALID_RESPONSE_TYPE_FOR_NON_BOT')
  invalidResponseTypeForNonBot('INVALID_RESPONSE_TYPE_FOR_NON_BOT'),
  @JsonValue('INVALID_SCOPE')
  invalidScope('INVALID_SCOPE'),
  @JsonValue('INVALID_STREAM_KEY_FORMAT')
  invalidStreamKeyFormat('INVALID_STREAM_KEY_FORMAT'),
  @JsonValue('INVALID_STREAM_THUMBNAIL_PAYLOAD')
  invalidStreamThumbnailPayload('INVALID_STREAM_THUMBNAIL_PAYLOAD'),
  @JsonValue('INVALID_SUDO_TOKEN')
  invalidSudoToken('INVALID_SUDO_TOKEN'),
  @JsonValue('INVALID_SUSPICIOUS_FLAGS_FORMAT')
  invalidSuspiciousFlagsFormat('INVALID_SUSPICIOUS_FLAGS_FORMAT'),
  @JsonValue('INVALID_SYSTEM_FLAG')
  invalidSystemFlag('INVALID_SYSTEM_FLAG'),
  @JsonValue('INVALID_TIMESTAMP')
  invalidTimestamp('INVALID_TIMESTAMP'),
  @JsonValue('INVALID_TOKEN')
  invalidToken('INVALID_TOKEN'),
  @JsonValue('INVALID_WEBAUTHN_AUTHENTICATION_COUNTER')
  invalidWebauthnAuthenticationCounter(
    'INVALID_WEBAUTHN_AUTHENTICATION_COUNTER',
  ),
  @JsonValue('INVALID_WEBAUTHN_CREDENTIAL_COUNTER')
  invalidWebauthnCredentialCounter('INVALID_WEBAUTHN_CREDENTIAL_COUNTER'),
  @JsonValue('INVALID_WEBAUTHN_CREDENTIAL')
  invalidWebauthnCredential('INVALID_WEBAUTHN_CREDENTIAL'),
  @JsonValue('INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT')
  invalidWebauthnPublicKeyFormat('INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT'),
  @JsonValue('INVITES_DISABLED')
  invitesDisabled('INVITES_DISABLED'),
  @JsonValue('IP_AUTHORIZATION_REQUIRED')
  ipAuthorizationRequired('IP_AUTHORIZATION_REQUIRED'),
  @JsonValue('IP_AUTHORIZATION_RESEND_COOLDOWN')
  ipAuthorizationResendCooldown('IP_AUTHORIZATION_RESEND_COOLDOWN'),
  @JsonValue('IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED')
  ipAuthorizationResendLimitExceeded('IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED'),
  @JsonValue('IP_BANNED')
  ipBanned('IP_BANNED'),
  @JsonValue('MAX_ANIMATED_EMOJIS')
  maxAnimatedEmojis('MAX_ANIMATED_EMOJIS'),
  @JsonValue('MAX_BOOKMARKS')
  maxBookmarks('MAX_BOOKMARKS'),
  @JsonValue('MAX_CATEGORY_CHANNELS')
  maxCategoryChannels('MAX_CATEGORY_CHANNELS'),
  @JsonValue('MAX_EMOJIS')
  maxEmojis('MAX_EMOJIS'),
  @JsonValue('MAX_FAVORITE_MEMES')
  maxFavoriteMemes('MAX_FAVORITE_MEMES'),
  @JsonValue('MAX_FRIENDS')
  maxFriends('MAX_FRIENDS'),
  @JsonValue('MAX_GROUP_DM_RECIPIENTS')
  maxGroupDmRecipients('MAX_GROUP_DM_RECIPIENTS'),
  @JsonValue('MAX_GROUP_DMS')
  maxGroupDms('MAX_GROUP_DMS'),
  @JsonValue('MAX_GUILD_CHANNELS')
  maxGuildChannels('MAX_GUILD_CHANNELS'),
  @JsonValue('MAX_GUILD_MEMBERS')
  maxGuildMembers('MAX_GUILD_MEMBERS'),
  @JsonValue('MAX_GUILD_ROLES')
  maxGuildRoles('MAX_GUILD_ROLES'),
  @JsonValue('MAX_GUILDS')
  maxGuilds('MAX_GUILDS'),
  @JsonValue('MAX_INVITES')
  maxInvites('MAX_INVITES'),
  @JsonValue('MAX_PACK_EXPRESSIONS')
  maxPackExpressions('MAX_PACK_EXPRESSIONS'),
  @JsonValue('MAX_PACKS')
  maxPacks('MAX_PACKS'),
  @JsonValue('MAX_PINS_PER_CHANNEL')
  maxPinsPerChannel('MAX_PINS_PER_CHANNEL'),
  @JsonValue('MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE')
  messageTotalAttachmentSizeTooLarge('MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE'),
  @JsonValue('MAX_REACTIONS')
  maxReactions('MAX_REACTIONS'),
  @JsonValue('MAX_STICKERS')
  maxStickers('MAX_STICKERS'),
  @JsonValue('MAX_WEBHOOKS_PER_CHANNEL')
  maxWebhooksPerChannel('MAX_WEBHOOKS_PER_CHANNEL'),
  @JsonValue('MAX_WEBHOOKS_PER_GUILD')
  maxWebhooksPerGuild('MAX_WEBHOOKS_PER_GUILD'),
  @JsonValue('MAX_WEBHOOKS')
  maxWebhooks('MAX_WEBHOOKS'),
  @JsonValue('NCMEC_ALREADY_SUBMITTED')
  ncmecAlreadySubmitted('NCMEC_ALREADY_SUBMITTED'),
  @JsonValue('NCMEC_SUBMISSION_FAILED')
  ncmecSubmissionFailed('NCMEC_SUBMISSION_FAILED'),
  @JsonValue('MEDIA_METADATA_ERROR')
  mediaMetadataError('MEDIA_METADATA_ERROR'),
  @JsonValue('METHOD_NOT_ALLOWED')
  methodNotAllowed('METHOD_NOT_ALLOWED'),
  @JsonValue('MISSING_ACCESS')
  missingAccess('MISSING_ACCESS'),
  @JsonValue('MISSING_ACL')
  missingAcl('MISSING_ACL'),
  @JsonValue('MISSING_AUTHORIZATION')
  missingAuthorization('MISSING_AUTHORIZATION'),
  @JsonValue('MISSING_CLIENT_SECRET')
  missingClientSecret('MISSING_CLIENT_SECRET'),
  @JsonValue('MISSING_EPHEMERAL_KEY')
  missingEphemeralKey('MISSING_EPHEMERAL_KEY'),
  @JsonValue('MISSING_IV')
  missingIv('MISSING_IV'),
  @JsonValue('MISSING_OAUTH_ADMIN_SCOPE')
  missingOauthAdminScope('MISSING_OAUTH_ADMIN_SCOPE'),
  @JsonValue('MISSING_OAUTH_FIELDS')
  missingOauthFields('MISSING_OAUTH_FIELDS'),
  @JsonValue('MISSING_OAUTH_SCOPE')
  missingOauthScope('MISSING_OAUTH_SCOPE'),
  @JsonValue('MISSING_PERMISSIONS')
  missingPermissions('MISSING_PERMISSIONS'),
  @JsonValue('MISSING_REDIRECT_URI')
  missingRedirectUri('MISSING_REDIRECT_URI'),
  @JsonValue('NO_ACTIVE_CALL')
  noActiveCall('NO_ACTIVE_CALL'),
  @JsonValue('NO_ACTIVE_SUBSCRIPTION')
  noActiveSubscription('NO_ACTIVE_SUBSCRIPTION'),
  @JsonValue('NOT_FOUND')
  notFound('NOT_FOUND'),
  @JsonValue('NOT_IMPLEMENTED')
  notImplemented('NOT_IMPLEMENTED'),
  @JsonValue('NO_PASSKEYS_REGISTERED')
  noPasskeysRegistered('NO_PASSKEYS_REGISTERED'),
  @JsonValue('NO_PENDING_DELETION')
  noPendingDeletion('NO_PENDING_DELETION'),
  @JsonValue('NO_USERS_WITH_FLUXERTAG_EXIST')
  noUsersWithFluxertagExist('NO_USERS_WITH_FLUXERTAG_EXIST'),
  @JsonValue('NO_VISIONARY_SLOTS_AVAILABLE')
  noVisionarySlotsAvailable('NO_VISIONARY_SLOTS_AVAILABLE'),
  @JsonValue('NOT_A_BOT_APPLICATION')
  notABotApplication('NOT_A_BOT_APPLICATION'),
  @JsonValue('NOT_FRIENDS_WITH_USER')
  notFriendsWithUser('NOT_FRIENDS_WITH_USER'),
  @JsonValue('NOT_OWNER_OF_ADMIN_API_KEY')
  notOwnerOfAdminApiKey('NOT_OWNER_OF_ADMIN_API_KEY'),
  @JsonValue('NSFW_CONTENT_AGE_RESTRICTED')
  nsfwContentAgeRestricted('NSFW_CONTENT_AGE_RESTRICTED'),
  @JsonValue('PACK_ACCESS_DENIED')
  packAccessDenied('PACK_ACCESS_DENIED'),
  @JsonValue('PASSKEY_AUTHENTICATION_FAILED')
  passkeyAuthenticationFailed('PASSKEY_AUTHENTICATION_FAILED'),
  @JsonValue('PASSKEYS_DISABLED')
  passkeysDisabled('PASSKEYS_DISABLED'),
  @JsonValue('PHONE_ALREADY_USED')
  phoneAlreadyUsed('PHONE_ALREADY_USED'),
  @JsonValue('PHONE_RATE_LIMIT_EXCEEDED')
  phoneRateLimitExceeded('PHONE_RATE_LIMIT_EXCEEDED'),
  @JsonValue('PHONE_REQUIRED_FOR_SMS_MFA')
  phoneRequiredForSmsMfa('PHONE_REQUIRED_FOR_SMS_MFA'),
  @JsonValue('PHONE_VERIFICATION_REQUIRED')
  phoneVerificationRequired('PHONE_VERIFICATION_REQUIRED'),
  @JsonValue('PREMIUM_PURCHASE_BLOCKED')
  premiumPurchaseBlocked('PREMIUM_PURCHASE_BLOCKED'),
  @JsonValue('PREVIEW_MUST_BE_JPEG')
  previewMustBeJpeg('PREVIEW_MUST_BE_JPEG'),
  @JsonValue('PROCESSING_FAILED')
  processingFailed('PROCESSING_FAILED'),
  @JsonValue('RATE_LIMITED')
  rateLimited('RATE_LIMITED'),
  @JsonValue('REDIRECT_URI_REQUIRED_FOR_NON_BOT')
  redirectUriRequiredForNonBot('REDIRECT_URI_REQUIRED_FOR_NON_BOT'),
  @JsonValue('REPORT_ALREADY_RESOLVED')
  reportAlreadyResolved('REPORT_ALREADY_RESOLVED'),
  @JsonValue('REPORT_BANNED')
  reportBanned('REPORT_BANNED'),
  @JsonValue('RESPONSE_VALIDATION_ERROR')
  responseValidationError('RESPONSE_VALIDATION_ERROR'),
  @JsonValue('SERVICE_UNAVAILABLE')
  serviceUnavailable('SERVICE_UNAVAILABLE'),
  @JsonValue('SESSION_TOKEN_MISMATCH')
  sessionTokenMismatch('SESSION_TOKEN_MISMATCH'),
  @JsonValue('SLOWMODE_RATE_LIMITED')
  slowmodeRateLimited('SLOWMODE_RATE_LIMITED'),
  @JsonValue('SMS_MFA_NOT_ENABLED')
  smsMfaNotEnabled('SMS_MFA_NOT_ENABLED'),
  @JsonValue('SMS_MFA_REQUIRES_TOTP')
  smsMfaRequiresTotp('SMS_MFA_REQUIRES_TOTP'),
  @JsonValue('SMS_VERIFICATION_UNAVAILABLE')
  smsVerificationUnavailable('SMS_VERIFICATION_UNAVAILABLE'),
  @JsonValue('SSO_REQUIRED')
  ssoRequired('SSO_REQUIRED'),
  @JsonValue('STREAM_KEY_CHANNEL_MISMATCH')
  streamKeyChannelMismatch('STREAM_KEY_CHANNEL_MISMATCH'),
  @JsonValue('STREAM_KEY_SCOPE_MISMATCH')
  streamKeyScopeMismatch('STREAM_KEY_SCOPE_MISMATCH'),
  @JsonValue('STREAM_THUMBNAIL_PAYLOAD_EMPTY')
  streamThumbnailPayloadEmpty('STREAM_THUMBNAIL_PAYLOAD_EMPTY'),
  @JsonValue('STRIPE_ERROR')
  stripeError('STRIPE_ERROR'),
  @JsonValue('STRIPE_GIFT_REDEMPTION_IN_PROGRESS')
  stripeGiftRedemptionInProgress('STRIPE_GIFT_REDEMPTION_IN_PROGRESS'),
  @JsonValue('STRIPE_INVALID_PRODUCT')
  stripeInvalidProduct('STRIPE_INVALID_PRODUCT'),
  @JsonValue('STRIPE_INVALID_PRODUCT_CONFIGURATION')
  stripeInvalidProductConfiguration('STRIPE_INVALID_PRODUCT_CONFIGURATION'),
  @JsonValue('STRIPE_NO_ACTIVE_SUBSCRIPTION')
  stripeNoActiveSubscription('STRIPE_NO_ACTIVE_SUBSCRIPTION'),
  @JsonValue('STRIPE_NO_PURCHASE_HISTORY')
  stripeNoPurchaseHistory('STRIPE_NO_PURCHASE_HISTORY'),
  @JsonValue('STRIPE_NO_SUBSCRIPTION')
  stripeNoSubscription('STRIPE_NO_SUBSCRIPTION'),
  @JsonValue('STRIPE_PAYMENT_NOT_AVAILABLE')
  stripePaymentNotAvailable('STRIPE_PAYMENT_NOT_AVAILABLE'),
  @JsonValue('STRIPE_SUBSCRIPTION_ALREADY_CANCELING')
  stripeSubscriptionAlreadyCanceling('STRIPE_SUBSCRIPTION_ALREADY_CANCELING'),
  @JsonValue('STRIPE_SUBSCRIPTION_NOT_CANCELING')
  stripeSubscriptionNotCanceling('STRIPE_SUBSCRIPTION_NOT_CANCELING'),
  @JsonValue('STRIPE_SUBSCRIPTION_PERIOD_END_MISSING')
  stripeSubscriptionPeriodEndMissing('STRIPE_SUBSCRIPTION_PERIOD_END_MISSING'),
  @JsonValue('STRIPE_WEBHOOK_NOT_AVAILABLE')
  stripeWebhookNotAvailable('STRIPE_WEBHOOK_NOT_AVAILABLE'),
  @JsonValue('STRIPE_WEBHOOK_SIGNATURE_INVALID')
  stripeWebhookSignatureInvalid('STRIPE_WEBHOOK_SIGNATURE_INVALID'),
  @JsonValue('STRIPE_WEBHOOK_SIGNATURE_MISSING')
  stripeWebhookSignatureMissing('STRIPE_WEBHOOK_SIGNATURE_MISSING'),
  @JsonValue('DONATION_AMOUNT_INVALID')
  donationAmountInvalid('DONATION_AMOUNT_INVALID'),
  @JsonValue('DONATION_MAGIC_LINK_EXPIRED')
  donationMagicLinkExpired('DONATION_MAGIC_LINK_EXPIRED'),
  @JsonValue('DONATION_MAGIC_LINK_INVALID')
  donationMagicLinkInvalid('DONATION_MAGIC_LINK_INVALID'),
  @JsonValue('DONATION_MAGIC_LINK_USED')
  donationMagicLinkUsed('DONATION_MAGIC_LINK_USED'),
  @JsonValue('DONOR_NOT_FOUND')
  donorNotFound('DONOR_NOT_FOUND'),
  @JsonValue('SUDO_MODE_REQUIRED')
  sudoModeRequired('SUDO_MODE_REQUIRED'),
  @JsonValue('TAG_ALREADY_TAKEN')
  tagAlreadyTaken('TAG_ALREADY_TAKEN'),
  @JsonValue('TEMPORARY_INVITE_REQUIRES_PRESENCE')
  temporaryInviteRequiresPresence('TEMPORARY_INVITE_REQUIRES_PRESENCE'),
  @JsonValue('TEST_HARNESS_DISABLED')
  testHarnessDisabled('TEST_HARNESS_DISABLED'),
  @JsonValue('TEST_HARNESS_FORBIDDEN')
  testHarnessForbidden('TEST_HARNESS_FORBIDDEN'),
  @JsonValue('TWO_FA_NOT_ENABLED')
  twoFaNotEnabled('TWO_FA_NOT_ENABLED'),
  @JsonValue('TWO_FACTOR_REQUIRED')
  twoFactorRequired('TWO_FACTOR_REQUIRED'),
  @JsonValue('UNAUTHORIZED')
  unauthorized('UNAUTHORIZED'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS')
  unclaimedAccountCannotAcceptFriendRequests(
    'UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS')
  unclaimedAccountCannotAddReactions('UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS')
  unclaimedAccountCannotCreateApplications(
    'UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS')
  unclaimedAccountCannotJoinGroupDms('UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS')
  unclaimedAccountCannotJoinOneOnOneVoiceCalls(
    'UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS')
  unclaimedAccountCannotJoinVoiceChannels(
    'UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES')
  unclaimedAccountCannotMakePurchases(
    'UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES')
  unclaimedAccountCannotSendDirectMessages(
    'UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS')
  unclaimedAccountCannotSendFriendRequests(
    'UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES')
  unclaimedAccountCannotSendMessages('UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES'),
  @JsonValue('UNKNOWN_CHANNEL')
  unknownChannel('UNKNOWN_CHANNEL'),
  @JsonValue('UNKNOWN_EMOJI')
  unknownEmoji('UNKNOWN_EMOJI'),
  @JsonValue('UNKNOWN_FAVORITE_MEME')
  unknownFavoriteMeme('UNKNOWN_FAVORITE_MEME'),
  @JsonValue('UNKNOWN_GIFT_CODE')
  unknownGiftCode('UNKNOWN_GIFT_CODE'),
  @JsonValue('UNKNOWN_GUILD')
  unknownGuild('UNKNOWN_GUILD'),
  @JsonValue('UNKNOWN_HARVEST')
  unknownHarvest('UNKNOWN_HARVEST'),
  @JsonValue('UNKNOWN_INVITE')
  unknownInvite('UNKNOWN_INVITE'),
  @JsonValue('UNKNOWN_MEMBER')
  unknownMember('UNKNOWN_MEMBER'),
  @JsonValue('UNKNOWN_MESSAGE')
  unknownMessage('UNKNOWN_MESSAGE'),
  @JsonValue('UNKNOWN_PACK')
  unknownPack('UNKNOWN_PACK'),
  @JsonValue('UNKNOWN_REPORT')
  unknownReport('UNKNOWN_REPORT'),
  @JsonValue('UNKNOWN_ROLE')
  unknownRole('UNKNOWN_ROLE'),
  @JsonValue('UNKNOWN_STICKER')
  unknownSticker('UNKNOWN_STICKER'),
  @JsonValue('UNKNOWN_SUSPICIOUS_FLAG')
  unknownSuspiciousFlag('UNKNOWN_SUSPICIOUS_FLAG'),
  @JsonValue('UNKNOWN_USER_FLAG')
  unknownUserFlag('UNKNOWN_USER_FLAG'),
  @JsonValue('UNKNOWN_USER')
  unknownUser('UNKNOWN_USER'),
  @JsonValue('UNKNOWN_VOICE_REGION')
  unknownVoiceRegion('UNKNOWN_VOICE_REGION'),
  @JsonValue('UNKNOWN_VOICE_SERVER')
  unknownVoiceServer('UNKNOWN_VOICE_SERVER'),
  @JsonValue('UNKNOWN_WEBAUTHN_CREDENTIAL')
  unknownWebauthnCredential('UNKNOWN_WEBAUTHN_CREDENTIAL'),
  @JsonValue('UNKNOWN_APPLICATION')
  unknownApplication('UNKNOWN_APPLICATION'),
  @JsonValue('UNKNOWN_WEBHOOK')
  unknownWebhook('UNKNOWN_WEBHOOK'),
  @JsonValue('UNSUPPORTED_RESPONSE_TYPE')
  unsupportedResponseType('UNSUPPORTED_RESPONSE_TYPE'),
  @JsonValue('USERNAME_NOT_AVAILABLE')
  usernameNotAvailable('USERNAME_NOT_AVAILABLE'),
  @JsonValue('UPDATE_FAILED')
  updateFailed('UPDATE_FAILED'),
  @JsonValue('USER_BANNED_FROM_GUILD')
  userBannedFromGuild('USER_BANNED_FROM_GUILD'),
  @JsonValue('USER_IP_BANNED_FROM_GUILD')
  userIpBannedFromGuild('USER_IP_BANNED_FROM_GUILD'),
  @JsonValue('USER_NOT_IN_VOICE')
  userNotInVoice('USER_NOT_IN_VOICE'),
  @JsonValue('USER_OWNS_GUILDS')
  userOwnsGuilds('USER_OWNS_GUILDS'),
  @JsonValue('VALIDATION_ERROR')
  validationError('VALIDATION_ERROR'),
  @JsonValue('VOICE_CHANNEL_FULL')
  voiceChannelFull('VOICE_CHANNEL_FULL'),
  @JsonValue('WEBAUTHN_CREDENTIAL_LIMIT_REACHED')
  webauthnCredentialLimitReached('WEBAUTHN_CREDENTIAL_LIMIT_REACHED'),

  /// Default value for all unparsed values, allows backward compatibility when adding new values on the backend.
  $unknown(null);

  const ApiErrorCode(this.json);

  factory ApiErrorCode.fromJson(String json) =>
      values.firstWhere((e) => e.json == json, orElse: () => $unknown);

  final String? json;

  String toJson() => json ?? 'null';

  @override
  String toString() => json ?? super.toString();

  /// Returns all defined enum values excluding the $unknown value.
  static List<ApiErrorCode> get $valuesDefined =>
      values.where((value) => value != $unknown).toList();
}
