// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import, invalid_annotation_target, unnecessary_import

import 'package:json_annotation/json_annotation.dart';

import 'embed_author_response.dart';
import 'embed_field_response.dart';
import 'embed_footer_response.dart';
import 'embed_media_response.dart';
import 'int32_type.dart';
import 'message_embed_child_response.dart';

part 'message_embed_response.g.dart';

@JsonSerializable()
class MessageEmbedResponse {
  const MessageEmbedResponse({
    required this.type,
    this.url,
    this.title,
    this.color,
    this.timestamp,
    this.description,
    this.author,
    this.image,
    this.thumbnail,
    this.footer,
    this.fields,
    this.provider,
    this.video,
    this.audio,
    this.nsfw,
    this.children,
  });

  factory MessageEmbedResponse.fromJson(Map<String, Object?> json) =>
      _$MessageEmbedResponseFromJson(json);

  /// The type of embed (e.g., rich, image, video, gifv, article, link)
  final String type;

  /// The URL of the embed
  final String? url;

  /// The title of the embed
  final String? title;

  /// The color code of the embed sidebar
  final Int32Type? color;

  /// The ISO 8601 timestamp of the embed content
  final DateTime? timestamp;

  /// The description of the embed
  final String? description;

  /// The author information of the embed
  final EmbedAuthorResponse? author;

  /// The image of the embed
  final EmbedMediaResponse? image;

  /// The thumbnail of the embed
  final EmbedMediaResponse? thumbnail;

  /// The footer of the embed
  final EmbedFooterResponse? footer;

  /// The fields of the embed
  final List<EmbedFieldResponse>? fields;

  /// The provider of the embed (e.g., YouTube, Twitter)
  final EmbedAuthorResponse? provider;

  /// The video of the embed
  final EmbedMediaResponse? video;

  /// The audio of the embed
  final EmbedMediaResponse? audio;

  /// Whether the embed is flagged as NSFW
  final bool? nsfw;

  /// Internal nested embeds generated by unfurlers
  final List<MessageEmbedChildResponse>? children;

  Map<String, Object?> toJson() => _$MessageEmbedResponseToJson(this);
}
